#!/bin/bash

BOLDGREEN="\e[1;32m"
ENDCOLOR="\e[0m"

USER="mart"
HOME="/home/$USER"
CFG="$HOME/.config"
DOTS="$HOME/git/dotfiles"

GITNAME="mart-mihkel"
GITMAIL="mart.mihkel.aun@gmail.com"

CORE_PKGS="base linux linux-firmware intel-ucode sudo man-db curl git neovim vim tmux openssl openssh sshfs networkmanager bash-completion"
COMMON_PKGS="neofetch btop ripgrep make gcc go r docker docker-compose docker-buildx containerd unzip zip"
DESKTOP_PKGS="hyprland hypridle hyprlock hyprpaper greetd waybar wofi dunst libnotify polkit-kde-agent brightnessctl alacritty noto-fonts-emoji noto-fonts-cjk ttf-ubuntu-mono-nerd bluez bluez-utils pamixer pipewire pipewire-alsa pipewire-pulse wireplumber grim slurp firefox ccid pcsclite gammastep"
YAY_PKGS="intel-undervolt auto-cpufreq wofi-emoji xdg-desktop-portal-hyprland xwaylandvideobridge slack-desktop qdigidoc4 discord"

if [[ -z "$1" || "$1" == "core" ]]; then
    echo -e "\n${BOLDGREEN}[core]${ENDCOLOR}\n"

    usermod -a -G wheel "$USER"
    pacman -S --needed --noconfirm $CORE_PKGS

    groupadd network
    usermod -a -G network "$USER"
    systemctl enable NetworkManager

    git config --global user.name "$GITNAME"
    git config --global user.email "$GITMAIL"
    git config --global core.editor nvim
    git config --global init.defaultBranch master

    su "$USER" -c "ln -sf '$DOTS/bash/.bashrc' '$HOME/.bashrc'"
    su "$USER" -c "ln -sf '$DOTS/bash/.bash_profile' '$HOME/.bash_profile'"
    su "$USER" -c "ln -sf '$DOTS/tmux/.tmux.conf' '$HOME/.tmux.conf'"
    su "$USER" -c "ln -sf '$DOTS/nvim' '$CFG'"
fi

if [[ -z "$1" || "$1" == "common" ]]; then
    echo -e "\n${BOLDGREEN}[common]${ENDCOLOR}\n"

    pacman -S --needed --noconfirm $COMMON_PKGS

    groupadd docker
    usermod -a -G docker "$USER"

    if [[ ! -e "$HOME/.rustup" ]]; then
        su "$USER" - c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
    fi

    if [[ ! -e "$HOME/.nvm" ]]; then
        su "$USER" -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash"
    fi
fi

if [[ -z "$1" || "$1" == "desktop" ]]; then
    echo -e "\n${BOLDGREEN}[desktop]${ENDCOLOR}\n"

    pacman -S --needed --noconfirm $DESKTOP_PKGS

    systemctl enable greetd.service
    systemctl enable pcscd.service

    ln -sf "$DOTS/greetd/config.toml" /etc/greetd/config.toml

    su "$USER" -c "ln -sf '$DOTS/alacritty' '$CFG'"
    su "$USER" -c "ln -sf '$DOTS/waybar' '$CFG'"
    su "$USER" -c "ln -sf '$DOTS/dunst' '$CFG'"
    su "$USER" -c "ln -sf '$DOTS/wofi' '$CFG'"
    su "$USER" -c "ln -sf '$DOTS/hypr' '$CFG'"
fi

if [[ "$1" == "clean" ]]; then
    echo -e "\n${BOLDGREEN}[clean]${ENDCOLOR}\n"

    pacman -D --asdeps $(pacman -Qqe)
    pacman -D --asexplicit $CORE_PKGS $COMMON_PKGS $DESKTOP_PKGS $YAY_PKGS yay
    pacman -Qdtq | pacman -Rns -
fi
