#!/bin/bash

BOLDGREEN="\e[1;32m"
ENDCOLOR="\e[0m"

USER="mart"
HOME="/home/$USER"
CFG="$HOME/.config"
DOTS="$HOME/git/dotfiles"

GITNAME="mart-mihkel"
GITMAIL="mart.mihkel.aun@gmail.com"

PKGS_CORE="base linux linux-firmware intel-ucode sudo man-db git curl wget neovim vim tmux openssl openssh net-tools networkmanager bash-completion"
PKGS_COMMON="neofetch btop ripgrep make gcc go r docker docker-compose docker-buildx containerd unzip zip"
PKGS_LSP="rust-analyzer lua-language-server typescript-language-server pyright"
PKGS_WAYLAND="hyprland hypridle hyprlock hyprpaper greetd waybar wofi dunst polkit-kde-agent alacritty grim slurp"
PKGS_HARDWARE="pamixer pipewire pipewire-alsa pipewire-pulse wireplumber bluez bluez-utils ccid pcsclite gammastep brightnessctl"
PKGS_DESKTOP="noto-fonts-emoji noto-fonts-cjk ttf-ubuntu-mono-nerd firefox"
PKGS_AUR="intel-undervolt auto-cpufreq wofi-emoji xdg-desktop-portal-hyprland xwaylandvideobridge slack-desktop qdigidoc4 discord"

if [[ -z "$1" || "$1" == "core" ]]; then
    echo -e "\n${BOLDGREEN}[core]${ENDCOLOR}\n"

    usermod -a -G wheel "$USER"
    pacman -S --needed --noconfirm $PKGS_CORE

    groupadd network
    usermod -a -G network "$USER"
    systemctl enable NetworkManager

    git config --global user.name "$GITNAME"
    git config --global user.email "$GITMAIL"
    git config --global core.editor nvim
    git config --global init.defaultBranch master

    su "$USER" -c "ln -sf '$DOTS/bash/.bashrc' '$HOME/.bashrc'"
    su "$USER" -c "ln -sf '$DOTS/bash/.bash_profile' '$HOME/.bash_profile'"
    su "$USER" -c "ln -sf '$DOTS/tmux/.tmux.conf' '$HOME/.tmux.conf'"
    su "$USER" -c "ln -sf '$DOTS/nvim' '$CFG'"
fi

if [[ -z "$1" || "$1" == "common" ]]; then
    echo -e "\n${BOLDGREEN}[common]${ENDCOLOR}\n"

    pacman -S --needed --noconfirm $PKGS_COMMON $PKGS_LSP

    groupadd docker
    usermod -a -G docker "$USER"

    if [[ ! -e "$HOME/.rustup" ]]; then
        su "$USER" - c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
    fi

    if [[ ! -e "$HOME/.nvm" ]]; then
        su "$USER" -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash"
    fi
fi

if [[ -z "$1" || "$1" == "desktop" ]]; then
    echo -e "\n${BOLDGREEN}[desktop]${ENDCOLOR}\n"

    pacman -S --needed --noconfirm $PKGS_WAYLAND $PKGS_HARDWARE $PKGS_DESKTOP

    systemctl enable greetd.service
    systemctl enable pcscd.service

    ln -sf "$DOTS/greetd/config.toml" /etc/greetd/config.toml

    su "$USER" -c "ln -sf '$DOTS/alacritty' '$CFG'"
    su "$USER" -c "ln -sf '$DOTS/waybar' '$CFG'"
    su "$USER" -c "ln -sf '$DOTS/dunst' '$CFG'"
    su "$USER" -c "ln -sf '$DOTS/wofi' '$CFG'"
    su "$USER" -c "ln -sf '$DOTS/hypr' '$CFG'"
fi

if [[ "$1" == "clean" ]]; then
    echo -e "\n${BOLDGREEN}[clean]${ENDCOLOR}\n"

    pacman -D --asdeps $(pacman -Qqe)
    pacman -D --asexplicit $PKGS_CORE $PKGS_COMMON $PKGS_LSP $PKGS_WAYLAND $PKGS_HARDWARE $PKGS_DESKTOP $PKGS_AUR yay
    pacman -Qdtq | pacman -Rns -
fi
