#!/bin/bash

BOLDGREEN="\e[1;32m"
ENDCOLOR="\e[0m"

if [[ -z $1 ]]; then
    echo "setup USER"
    exit 1
fi

USER="$1"
HOME="/home/$USER"
CONF="$HOME/.config"
DOTS="$HOME/git/dotfiles"

PKGS_I3="i3 xorg-server xorg-xinit xorg-xset xorg-xrandr xclip autotiling gammastep greetd maim rofi rofi-emoji"
PKGS_HARDWARE="pipewire pipewire-alsa pipewire-pulse wireplumber bluez bluez-utils ccid pcsclite brightnessctl"
PKGS_DESKTOP="alacritty firefox dolphin zoom slack-desktop qdigidoc4"
PKGS_FONTS="noto-fonts noto-fonts-emoji noto-fonts-cjk ttf-jetbrains-mono-nerd "

echo -e "[${BOLDGREEN}packages${ENDCOLOR}]"

su aur -c "yay -S --needed --noconfirm $PKGS_I3 $PKGS_HARDWARE $PKGS_DESKTOP $PKGS_FONTS"

echo -e "[${BOLDGREEN}services${ENDCOLOR}]"

systemctl enable pcscd.service
systemctl enable bluetooth.service

echo -e "[${BOLDGREEN}configs${ENDCOLOR}]"

ln -sf $DOTS/greetd/config.toml /etc/greetd/config.toml

su "$USER" -c "
    ln -sf $DOTS/xorg/.xinitrc $HOME/.xinitrc
    ln -sf $DOTS/i3blocks $CONF
    ln -sf $DOTS/i3 $CONF

    ln -sf $DOTS/alacritty $CONF
    ln -sf $DOTS/rofi $CONF
"
