#!/bin/bash

BOLDGREEN="\e[1;32m"
ENDCOLOR="\e[0m"

if [[ -z $1 ]]; then
    echo "setup USER"
    exit 1
fi

USER="$1"
HOME="/home/$USER"
CONF="$HOME/.config"
DOTS="$HOME/git/dotfiles"

PKGS_CORE="base base-devel linux-lts linux-firmware intel-ucode"
PKGS_COMMON="sudo man-db bash-completion git curl wget neovim vim tmux openssl openssh networkmanager intel-undervolt auto-cpufreq wol net-tools"
PKGS_EXTRA="fastfetch ripgrep cargo cmake make nodejs gcc uv jq zip unzip cloudflared tree docker docker-compose docker-buildx containerd"

if ! id -u aur > /dev/null 2>&1; then
    echo -e "[${BOLDGREEN}aur user${ENDCOLOR}]"

    useradd -m aur

    echo "aur   ALL = (root) NOPASSWD: /usr/bin/makepkg, /usr/bin/pacman" > /etc/sudoers.d/aur
fi

if ! command -v yay &> /dev/null; then
    echo -e "[${BOLDGREEN}aur helper${ENDCOLOR}]"

    pacman -S --needed --noconfirm base-devel git
    su aur -c "
        git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin

        pushd /tmp/yay-bin
        makepkg -si --needed --noconfirm
        popd

        rm -rf /tmp/yay-bin
    "
fi

echo -e "[${BOLDGREEN}packages${ENDCOLOR}]"

su aur -c "yay -S --needed --noconfirm $PKGS_CORE $PKGS_COMMON $PKGS_EXTRA"

echo -e "[${BOLDGREEN}groups${ENDCOLOR}]"

groupadd -f docker
groupadd -f network

usermod -a -G wheel $USER
usermod -a -G docker $USER
usermod -a -G network $USER

echo -e "[${BOLDGREEN}services${ENDCOLOR}]"

systemctl enable docker.service
systemctl enable NetworkManager
systemctl enable intel-undervolt.service

auto_cpufreq --install

echo -e "[${BOLDGREEN}configs${ENDCOLOR}]"

ln -sf $DOTS/greetd/config.toml /etc/greetd/config.toml

su "$USER" -c "
    ln -sf $DOTS/bash/.bashrc $HOME/.bashrc
    ln -sf $DOTS/nvim $CONF
    ln -sf $DOTS/tmux $CONF
"
