# vim: ft=cfg

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    resize_on_border = true
    allow_tearing = false
    layout = dwindle

    col.active_border = rgb(000000)
    col.inactive_border = rgba(00000000)
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    drop_shadow = false
}

animations {
    animation = global, 1, 4, default
    animation = windows, 1, 4, default, popin 80%
}

dwindle {
    pseudotile = true
    preserve_split = true
}

input {
    kb_layout = ee
    repeat_rate = 32
    repeat_delay = 256
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

gestures {
    workspace_swipe = true
}

cursor {
    inactive_timeout = 3
}

misc {
    disable_hyprland_logo = true
}

monitor=,preferred,auto,1,mirror,eDP-1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

windowrulev2 = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrulev2 = noanim, class:^(xwaylandvideobridge)$
windowrulev2 = noblur, class:^(xwaylandvideobridge)$

bind = SUPER, R, exec, wofi --show run --term alacritty
bind = SUPER, N, exec, pidof hyprlock || hyprlock
bind = SUPER, W, exec, pkill -SIGUSR1 waybar
bind = SUPER, code:60, exec, wofi-emoji
bind = SUPER, Q, exec, alacritty

bind = SUPER, V, togglefloating,
bind = SUPER, S, togglesplit,
bind = SUPER, C, killactive,
bind = SUPER, F, fullscreen,
bind = SUPER, P, pseudo,
bind = SUPER, M, exit,

bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMicMute, exec, pamixer --default-source -t
bind = , XF86AudioMute, exec, pamixer -t

bind = , XF86MonBrightnessDown, exec, brightnessctl s 2%-
bind = , XF86MonBrightnessUp, exec, brightnessctl s +2%

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

bind = SUPER, 1, focusworkspaceoncurrentmonitor, 1
bind = SUPER, 2, focusworkspaceoncurrentmonitor, 2
bind = SUPER, 3, focusworkspaceoncurrentmonitor, 3
bind = SUPER, 4, focusworkspaceoncurrentmonitor, 4
bind = SUPER, 5, focusworkspaceoncurrentmonitor, 5
bind = SUPER, 6, focusworkspaceoncurrentmonitor, 6
bind = SUPER, 7, focusworkspaceoncurrentmonitor, 7
bind = SUPER, 8, focusworkspaceoncurrentmonitor, 8
bind = SUPER, 9, focusworkspaceoncurrentmonitor, 9
bind = SUPER, 0, focusworkspaceoncurrentmonitor, 10

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gammastep -l 59.4370:24.7536 -t 6500:4500 -m wayland
exec-once = systemctl --user start plasma-polkit-agent
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprlock
exec-once = waybar
